seed: 0
max_steps: 50000000
game: hexners_game_fixed_state
save_dir: results/
turn_based: false
group_name: mmd_final
experiment_dir: results/mmd_final/mmd/hexners_game_fixed_state/2025-05-08_03-55-21-564598_20b8fc
compute_exploitability: false
compute_exploitability_every: 100000
run_in_safe_mode: false
job_id: -1
algorithm:
  algorithm_name: mmd
  learning_rate: 2.5e-05
  eval_every: 10
  cuda: false
  num_envs: 128
  num_steps: 64
  anneal_lr: true
  gae: true
  gamma: 0.99
  gae_lambda: 0.95
  num_minibatches: 4
  update_epochs: 4
  norm_adv: true
  clip_coef: 0.2
  clip_vloss: true
  ent_coef: 0.025
  vf_coef: 0.5
  max_grad_norm: 5
  target_kl: null
  kl_coef: 0.001
